### ISSUE TITLE
zqm permission denied

### ISSUE THREAD

**Issue by Dzhange** [threedworld-mit/tdw#166]
Hi,

When I run the starter python code on my WINDOWS laptop, 
in
`# c = Controller()` 
the code breaks down and it says
```
Traceback (most recent call last):
  File ".\twd_test.py", line 3, in <module>
    c = Controller(port=1071, launch_build=False)
  File "C:\Users\25457\AppData\Roaming\Python\Python37\site-packages\tdw\controller.py", line 48, in __init__
    self.socket.bind('tcp://*:' + str(port))        
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
    raise ZMQError(errno)
zmq.error.ZMQError: Permission denied
```
I guess the problem has something to do with the firewall, do you know any fixation to it?

Currently I'm running the binary with `twd.exe -port 10080` and change the error line into `c = Controller(port=10080, launch_build=False)`, seems it works, but I hopt there is a better way to avoid this

**Comment by alters-mit** [comment]
@Dzhange Closing this ticket. This error means that there is a build or controller process that is still running on the same port. Close all instances of the TDW controller and build and your code should work.
