### ISSUE TITLE
Exec format error when downloading on Raspberry Pi 4

### ISSUE THREAD

**Issue by ojames22** [threedworld-mit/tdw#364]
Hello,

I have been trying to install TDW on a raspberry pi 4 and have continuously received an Exec format error when I run the test:

`Traceback (most recent call last):
  File "tdwtest.py", line 3, in <module>
    c = Controller()
  File "/usr/local/lib/python3.7/dist-packages/tdw/controller.py", line 58, in __init__
    Controller.launch_build(port=port)
  File "/usr/local/lib/python3.7/dist-packages/tdw/controller.py", line 521, in launch_build
    Popen([str(Build.BUILD_PATH.resolve()), "-port "+str(port)])
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/tdw_build/TDW/TDW.x86_64'`

I've reinstalled TDW numerous times and made sure that my RP is compatible, according to the system requirements. What could be causing this error?

**Comment by alters-mit** [comment]
`TDW.x86_64` is a binary executable. It's never been tested on a Raspberry Pi before. What's the use case for running TDW on RP? What distro are you using?

**Comment by alters-mit** [comment]
Closed due to inactivity
