### ISSUE TITLE
AssetBundleCreator only generates assets for windows

### ISSUE THREAD

**Issue by dsp05** [threedworld-mit/tdw#84]
Hi, I ran `local_object.py` on Windows 10 and got the following error:

```
Converting a .fbx file to .obj
Running V-HACD on a .obj file (this might take awhile).
Created: cube.wrl
Removed V-HACD log file.
Removed superfluous .obj file: cube.obj
Converting .wrl to .obj
Created C:\Users\dsp\dev\projects\tdw\tdw\Python\example_controllers\cube_colliders.obj from .wrl file.
Copying files into the Unity project.
Copied files into the Unity project.
Creating the prefab...
Created the prefab.
Creating local asset bundles
Traceback (most recent call last):
  File ".\local_object.py", line 45, in <module>
    LocalObject.run()
  File ".\local_object.py", line 18, in run
    asset_bundle_paths, record_path = AssetBundleCreator().create_asset_bundle("cube.fbx", True, 123, "", 1)
  File "C:\Users\dsp\dev\projects\tdw\venv\lib\site-packages\tdw\asset_bundle_creator.py", line 97, in create_asset_bundle
    asset_bundle_paths = self.prefab_to_asset_bundle(prefab_path, model_name)
  File "C:\Users\dsp\dev\projects\tdw\venv\lib\site-packages\tdw\asset_bundle_creator.py", line 536, in prefab_to_asset_bundle
    assert bundle_path.exists(), f"Missing asset bundle: {asset_bundle_platform}"
AssertionError: Missing asset bundle: StandaloneOSX
```
In `asset_bundle_creator\Assets\NewAssetBundles\cube` I can see `StandaloneOSX` and `StandaloneLinux64`, but they are empty folders. `StandaloneWindows64` contains files for the new model.

Did I miss something?

**Comment by dsp05** [comment]
I also tested on macOS and got a similar error. Only `StandaloneOSX` was generated, others are empty.

**Comment by alters-mit** [comment]
@dsp05 Please attach your Unity Editor log: `C:\Users\username\AppData\Local\Unity\Editor\Editor.log`

**Comment by dsp05** [comment]
I checked the log and it said `required module is not installed`. I forgot to enable the build options for other platforms. It's resolved now. 
Thanks!
